=== Heber-Modelo/heber-modelo/src/main/resources/static/diagramas/.diagrama.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "properties": {
    "nome": {
      "type": "string"
    },
    "chaveI18N": {
      "type": "string"
    },
    "exigeAbaExclusiva": {
      "type": "boolean"
    },
    "elementos": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "nome": {
            "type": "string"
          },
          "tipo": {
            "type": "string"
          },
          "chaveI18N": {
            "type": "string"
          }
        },
        "required": ["nome", "tipo", "chaveI18N"]
      }
    }
  },
  "required": ["nome", "chaveI18N", "exigeAbaExclusiva", "elementos"]
}

=== Heber-Modelo/heber-modelo/src/main/resources/static/diagramas/der.json
{
  "$schema": ".diagrama.schema.json",
  "nome": "Diagrama Entidade Relacionamento",
  "chaveI18N": "diagram.entity.title",
  "exigeAbaExclusiva": false,
  "elementos": [
    {
      "nome": "agregação",
      "tipo": "agregacao",
      "chaveI18N": "element.aggregation"
    },
    {
      "nome": "atributo",
      "tipo": "atributo_der",
      "chaveI18N": "element.entity-attribute"
    },
    {
      "nome": "entidade",
      "tipo": "entidade",
      "chaveI18N": "element.entity"
    },
    {
      "nome": "especialização",
      "tipo": "especializacao",
      "chaveI18N": "element.specialization"
    },
    {
      "nome": "nota",
      "tipo": "nota",
      "chaveI18N": "element.note"
    },
    {
      "nome": "relacionamento",
      "tipo": "relacionamento",
      "chaveI18N": "element.relationship"
    },
    {
      "nome": "texto",
      "tipo": "texto",
      "chaveI18N": "element.text"
    }
  ]
}

=== Heber-Modelo/heber-modelo/src/main/resources/static/diagramas/ddd.json
{
  "$schema": ".diagrama.schema.json",
  "nome": "Dicionário de Dados",
  "chaveI18N": "diagram.dictionary.title",
  "exigeAbaExclusiva": true,
  "elementos": [
    {
      "nome": "Tabela Dicionário de Dados",
      "tipo": "tabela_dicionario",
      "chaveI18N": "element.dictionary-table"
    }
  ]
}

=== Heber-Modelo/heber-modelo/src/main/resources/static/diagramas/drl.json
{
  "$schema": ".diagrama.schema.json",
  "nome": "Diagrama do Modelo Relacional",
  "chaveI18N": "diagram.relational.title",
  "exigeAbaExclusiva": false,
  "elementos": [
    {
      "nome": "tabela",
      "tipo": "tabela_relacional",
      "chaveI18N": "element.relational-table"
    },
    {
      "nome": "cardinalidade",
      "tipo": "cardinalidade",
      "chaveI18N": "element.entity-cardinality"
    },
    {
      "nome": "nota",
      "tipo": "nota",
      "chaveI18N": "element.note"
    },
    {
      "nome": "texto",
      "tipo": "texto",
      "chaveI18N": "element.text"
    }
  ]
}

=== Heber-Modelo/heber-modelo/src/main/resources/static/diagramas/mlr.json
{
  "$schema": ".diagrama.schema.json",
  "nome": "Descrição do Modelo Relacional",
  "chaveI18N": "diagram.relational-model.title",
  "exigeAbaExclusiva": true,
  "elementos": [
    {
      "nome": "Editor de Descrição Relacional",
      "tipo": "editor_descricao_relacional",
      "chaveI18N": "element.relational-model-editor"
    }
  ]
}
