=== Heber-Modelo/heber-modelo/src/main/resources/static/elementos/.elemento.schema.json
{
  "$id": "",
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "title": "JSON Schema para os JSONs de definição de cada elemento de diagrama",
  "type": [
    "object"
  ],
  "properties": {
    "classesElemento": {
      "description": "Define quais classes este tipo de elemento deve ter.",
      "type": ["array"],
      "items": {
        "type": "string"
      }
    },
    "recebePontoExtensor": {
      "type": "boolean"
    },
    "recebeSetaConectora": {
      "type": "boolean"
    },
    "valorHtmlInterno": {
      "description": "Define a estrutura interna do HTML deste tipo de elemento",
      "type": ["string"]
    },
    "propriedades": {
      "description": "Define as propriedades deste tipo de elemento que podem ser editadas",
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "chaveI18nLabel": {
            "type": "string"
          },
          "chaveI18nValorInicial": {
            "type": "string"
          },
          "classeElemento": {
            "type": "string"
          },
          "nomePropriedade": {
            "type": "string"
          },
          "sufixo": {
            "type": "string"
          },
          "chavesI18nLabelsValoresPermitidos": {
            "type": "array",
            "items": { "type": "string" }
          },
          "valoresPermitidos": {
            "type": "array",
            "items": { "type": "string" }
          }
        },
        "required": [
          "chaveI18nLabel",
          "classeElemento",
          "nomePropriedade",
          "sufixo"
        ]
      }
    }
  },
  "required": [
    "classesElemento",
    "valorHtmlInterno",
    "recebePontoExtensor",
    "recebeSetaConectora",
    "propriedades"
  ]
}

=== Heber-Modelo/heber-modelo/src/main/resources/static/elementos/entidade_relacional.json
{
  "$schema": ".elemento.schema.json",
  "valorHtmlInterno": "<div contenteditable=\"true\" spellcheck=\"true\" class=\"nome\">tbEntidade</div><div class=\"atributo\" onmouseup=\"callbackAlterarAtributoRelacional(event)\"><span class=\"chave\"><span class=\"desc-chave\"></span></span><span contenteditable=\"true\" spellcheck=\"true\" class=\"texto\">atributo: tipo</span></div><button onclick=\"callbackCriarAtributoRelacional(event)\">+</button>",
  "classesElemento": ["elemento-entidade-relacional"],
  "recebePontoExtensor": true,
  "recebeSetaConectora": true,
  "propriedades": [
    {
      "chaveI18nLabel": "element.property.name.label",
      "chaveI18nValorInicial": "element.property.default-name.relational-entity",
      "classeElemento": "nome",
      "nomePropriedade": "innerText",
      "sufixo": ""
    }
  ]
}

=== Heber-Modelo/heber-modelo/src/main/resources/static/elementos/tabela_relacional.json
{
  "$schema": ".elemento.schema.json",
  "valorHtmlInterno": "<div contenteditable=\"true\" spellcheck=\"true\" class=\"nome\">tbEntidade</div><div class=\"atributo\"><span class=\"chave\"><svg class=\"chave-escondida\"></svg></span><span contenteditable=\"true\" spellcheck=\"true\" class=\"texto\">atributo: tipo</span></div><button class=\"remover-atributo\">-</button><button class=\"adicionar-atributo\">+</button>",
  "classesElemento": ["elemento-tabela-relacional"],
  "recebePontoExtensor": true,
  "recebeSetaConectora": true,
  "propriedades": [
    {
      "chaveI18nLabel": "element.property.font-size.label",
      "classeElemento": "nome",
      "nomePropriedade": "style.font-size",
      "sufixo": "pt"
    },
    {
      "chaveI18nLabel": "element.property.name.label",
      "chaveI18nValorInicial": "element.property.default-name.relational-table",
      "classeElemento": "nome",
      "nomePropriedade": "innerText",
      "sufixo": ""
    },
    {
      "chaveI18nLabel": "element.property.height.label",
      "classeElemento": "elemento-tabela-relacional",
      "nomePropriedade": "style.height",
      "sufixo": "px"
    },
    {
      "chaveI18nLabel": "element.property.width.label",
      "classeElemento": "elemento-tabela-relacional",
      "nomePropriedade": "style.width",
      "sufixo": "px"
    },
    {
      "chaveI18nLabel": "element.property.x.label",
      "classeElemento": "elemento-tabela-relacional",
      "nomePropriedade": "style.left",
      "sufixo": "px"
    },
    {
      "chaveI18nLabel": "element.property.y.label",
      "classeElemento": "elemento-tabela-relacional",
      "nomePropriedade": "style.top",
      "sufixo": "px"
    },
    {
      "chaveI18nLabel": "element.property.attribute.key.label",
      "classeElemento": "chave",
      "nomePropriedade": "child.attribute-key",
      "sufixo": "",
      "chavesI18nLabelsValoresPermitidos": [
        "element.property-value.attribute.key.none",
        "element.property-value.attribute.key.primary",
        "element.property-value.attribute.key.foreign"
      ],
      "valoresPermitidos": ["NONE", "PRIMARY", "FOREIGN"]
    },
    {
      "chaveI18nLabel": "element.property.attribute.name.label",
      "chaveI18nValorInicial": "element.property.default-name.attribute-name",
      "classeElemento": "texto",
      "nomePropriedade": "child.innerText",
      "sufixo": ""
    }
  ]
}

=== Heber-Modelo/heber-modelo/src/main/resources/static/elementos/atributo_der.json
{
  "$schema": ".elemento.schema.json",
  "valorHtmlInterno": "<div class=\"marcador-atributo\" onclick=\"callbackMarcador(event)\"></div><div  onmouseup=\"callbackInverterAtributo(event)\" contenteditable=\"true\" spellcheck=\"true\" class=\"nome\">atributo</div>",
  "classesElemento": ["elemento-atributo"],
  "recebePontoExtensor": false,
  "recebeSetaConectora": true,
  "propriedades": [
    {
      "chaveI18nLabel": "element.property.font-size.label",
      "classeElemento": "nome",
      "nomePropriedade": "style.font-size",
      "sufixo": "pt"
    },
    {
      "chaveI18nLabel": "element.property.x.label",
      "classeElemento": "elemento-atributo",
      "nomePropriedade": "style.left",
      "sufixo": "px"
    },
    {
      "chaveI18nLabel": "element.property.y.label",
      "classeElemento": "elemento-atributo",
      "nomePropriedade": "style.top",
      "sufixo": "px"
    },
    {
      "chaveI18nLabel": "element.property.name.label",
      "chaveI18nValorInicial": "element.property.default-name.attribute",
      "classeElemento": "nome",
      "nomePropriedade": "innerText",
      "sufixo": ""
    },
    {
      "chaveI18nLabel": "element.property.attribute-type.label",
      "classeElemento": "elemento-atributo",
      "nomePropriedade": "attributeType",
      "sufixo": "",
      "chavesI18nLabelsValoresPermitidos": [
        "element.property.attribute-type.normal.label",
        "element.property.attribute-type.derived.label",
        "element.property.attribute-type.primary-key.label"
      ],
      "valoresPermitidos": ["NORMAL", "DERIVADO", "CHAVE_PRIMARIA"]
    }
  ]
}

=== Heber-Modelo/heber-modelo/src/main/resources/static/elementos/tabela_dicionario.json
{
  "$schema": ".elemento.schema.json",
  "valorHtmlInterno": "<table><caption contenteditable=\"true\" spellcheck=\"true\" class=\"nome\"></caption><thead><tr><th scope=\"col\" class=\"nome-atributo\"></th><th scope=\"col\" class=\"description\"></th><th scope=\"col\" class=\"tipo\"></th><th scope=\"col\" class=\"tamanho\"></th><th scope=\"col\" class=\"nulo\"></th><th scope=\"col\" class=\"regra\"></th><th scope=\"col\" class=\"chave\"></th><th scope=\"col\" class=\"default\"></th><th scope=\"col\" class=\"unique\"></th></tr></thead><tbody><tr><th scope=\"row\"><p contenteditable=\"true\" spellcheck=\"true\"></p></th><td><p contenteditable=\"true\" spellcheck=\"true\"><p/></td><td><p contenteditable=\"true\" spellcheck=\"true\"></p></td><td><p contenteditable=\"true\" spellcheck=\"true\"></p></td><td><p contenteditable=\"true\" spellcheck=\"true\"></p></td><td><p contenteditable=\"true\" spellcheck=\"true\"></p></td><td><p contenteditable=\"true\" spellcheck=\"true\"></p></td><td><p contenteditable=\"true\" spellcheck=\"true\"></p></td><td><p contenteditable=\"true\" spellcheck=\"true\"></p></td></tr></tbody></table><div><button onclick=\"criarLinha(event)\">+</button><button onclick=\"excluirLinha(event)\">-</button></div>",
  "classesElemento": ["elemento-dicionario-dados"],
  "recebePontoExtensor": false,
  "recebeSetaConectora": false,
  "propriedades": [
    {
      "chaveI18nLabel": "element.property.name.label",
      "chaveI18nValorInicial": "element.property.default-name.entity",
      "classeElemento": "nome",
      "nomePropriedade": "innerText",
      "sufixo": ""
    },
    {
      "chaveI18nLabel": "element.property.attribute-name.label",
      "chaveI18nValorInicial": "element.property.default-name.attribute-label",
      "classeElemento": "nome-atributo",
      "nomePropriedade": "innerText",
      "sufixo": ""
    },
    {
      "chaveI18nLabel": "element.property.description.label",
      "chaveI18nValorInicial": "element.property.default-name.description-label",
      "classeElemento": "description",
      "nomePropriedade": "innerText",
      "sufixo": ""
    },
    {
      "chaveI18nLabel": "element.property.type.label",
      "chaveI18nValorInicial": "element.property.default-name.type-label",
      "classeElemento": "tipo",
      "nomePropriedade": "innerText",
      "sufixo": ""
    },
    {
      "chaveI18nLabel": "element.property.size.label",
      "chaveI18nValorInicial": "element.property.default-name.size-label",
      "classeElemento": "tamanho",
      "nomePropriedade": "innerText",
      "sufixo": ""
    },
    {
      "chaveI18nLabel": "element.property.nullable.label",
      "chaveI18nValorInicial": "element.property.default-name.nullable-label",
      "classeElemento": "nulo",
      "nomePropriedade": "innerText",
      "sufixo": ""
    },
    {
      "chaveI18nLabel": "element.property.check.label",
      "chaveI18nValorInicial": "element.property.default-name.check-label",
      "classeElemento": "regra",
      "nomePropriedade": "innerText",
      "sufixo": ""
    },
    {
      "chaveI18nLabel": "element.property.key.label",
      "chaveI18nValorInicial": "element.property.default-name.key-label",
      "classeElemento": "chave",
      "nomePropriedade": "innerText",
      "sufixo": ""
    },
    {
      "chaveI18nLabel": "element.property.default.label",
      "chaveI18nValorInicial": "element.property.default-name.default-label",
      "classeElemento": "default",
      "nomePropriedade": "innerText",
      "sufixo": ""
    },
    {
      "chaveI18nLabel": "element.property.unique.label",
      "chaveI18nValorInicial": "element.property.default-name.unique-label",
      "classeElemento": "unique",
      "nomePropriedade": "innerText",
      "sufixo": ""
    }
  ]
}

=== Heber-Modelo/heber-modelo/src/main/resources/static/elementos/conexao_reta.json
{
  "$schema": ".elemento.schema.json",
  "valorHtmlInterno": "<div class=\"ponto ponto-norte\"><div class=\"ponto-norte-valor\"></div><div class=\"parte-vertical\"></div><div class=\"parte-horizontal\"></div><div class=\"ponto ponto-sul\"><div class=\"ponto-sul-valor\"></div></div>",
  "classesElemento": ["elemento-conexao-reta"],
  "recebePontoExtensor": false,
  "recebeSetaConectora": false,
  "propriedades": [
    {
      "chaveI18nLabel": "element.property.position-north-point.label",
      "classeElemento": "ponto-norte-valor",
      "nomePropriedade": "posicao-ponto-norte",
      "sufixo": "",
      "chavesI18nLabelsValoresPermitidos": [
        "element.property-value.north.label",
        "element.property-value.south.label",
        "element.property-value.east.label",
        "element.property-value.west.label"
      ],
      "valoresPermitidos": ["NORTE", "SUL", "LESTE", "OESTE"]
    },
    {
      "chaveI18nLabel": "element.property.position-south-point.label",
      "classeElemento": "ponto-sul-valor",
      "nomePropriedade": "posicao-ponto-sul",
      "sufixo": "",
      "chavesI18nLabelsValoresPermitidos": [
        "element.property-value.north.label",
        "element.property-value.south.label",
        "element.property-value.east.label",
        "element.property-value.west.label"
      ],
      "valoresPermitidos": ["NORTE", "SUL", "LESTE", "OESTE"]
    }
  ]
}

=== Heber-Modelo/heber-modelo/src/main/resources/static/elementos/texto.json
{
  "$schema": ".elemento.schema.json",
  "valorHtmlInterno": "<div class=\"texto\" contenteditable=\"true\" spellcheck=\"true\">Texto</div>",
  "classesElemento": [
    "elemento-texto"
  ],
  "recebePontoExtensor": false,
  "recebeSetaConectora": true,
  "propriedades": [
    {
      "chaveI18nLabel": "element.property.font-size.label",
      "classeElemento": "texto",
      "nomePropriedade": "style.font-size",
      "sufixo": "pt"
    },
    {
      "chaveI18nLabel": "element.property.text.label",
      "chaveI18nValorInicial": "element.property.default-name.text",
      "classeElemento": "texto",
      "nomePropriedade": "innerText",
      "sufixo": ""
    },
    {
      "chaveI18nLabel": "element.property.height.label",
      "classeElemento": "elemento-texto",
      "nomePropriedade": "style.height",
      "sufixo": "px"
    },
    {
      "chaveI18nLabel": "element.property.width.label",
      "classeElemento": "elemento-texto",
      "nomePropriedade": "style.width",
      "sufixo": "px"
    },
    {
      "chaveI18nLabel": "element.property.x.label",
      "classeElemento": "elemento-texto",
      "nomePropriedade": "style.left",
      "sufixo": "px"
    },
    {
      "chaveI18nLabel": "element.property.y.label",
      "classeElemento": "elemento-texto",
      "nomePropriedade": "style.top",
      "sufixo": "px"
    }
  ]
}
