=== Heber-Modelo/heber-modelo/src/main/resources/static/elementos/.elemento.schema.json
{
  "$id": "",
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "title": "JSON Schema para os JSONs de definição de cada elemento de diagrama",
  "type": [
    "object"
  ],
  "properties": {
    "classesElemento": {
      "description": "Define quais classes este tipo de elemento deve ter.",
      "type": ["array"],
      "items": {
        "type": "string"
      }
    },
    "recebePontoExtensor": {
      "type": "boolean"
    },
    "recebeSetaConectora": {
      "type": "boolean"
    },
    "valorHtmlInterno": {
      "description": "Define a estrutura interna do HTML deste tipo de elemento",
      "type": ["string"]
    },
    "propriedades": {
      "description": "Define as propriedades deste tipo de elemento que podem ser editadas",
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "chaveI18nLabel": {
            "type": "string"
          },
          "chaveI18nValorInicial": {
            "type": "string"
          },
          "classeElemento": {
            "type": "string"
          },
          "nomePropriedade": {
            "type": "string"
          },
          "sufixo": {
            "type": "string"
          },
          "chavesI18nLabelsValoresPermitidos": {
            "type": "array",
            "items": { "type": "string" }
          },
          "valoresPermitidos": {
            "type": "array",
            "items": { "type": "string" }
          }
        },
        "required": [
          "chaveI18nLabel",
          "classeElemento",
          "nomePropriedade",
          "sufixo"
        ]
      }
    }
  },
  "required": [
    "classesElemento",
    "valorHtmlInterno",
    "recebePontoExtensor",
    "recebeSetaConectora",
    "propriedades"
  ]
}

=== Heber-Modelo/heber-modelo/src/main/resources/static/elementos/especializacao.json
{
  "$schema": ".elemento.schema.json",
  "valorHtmlInterno": "<div></div>",
  "classesElemento": ["elemento-especializacao"],
  "recebePontoExtensor": true,
  "recebeSetaConectora": true,
  "propriedades": [
    {
      "chaveI18nLabel": "element.property.rotation.label",
      "classeElemento": "elemento-especializacao",
      "nomePropriedade": "style.rotate",
      "sufixo": "deg"
    }
  ]
}

=== Heber-Modelo/heber-modelo/src/main/resources/static/elementos/nota.json
{
  "$schema": ".elemento.schema.json",
  "valorHtmlInterno": "<div contenteditable=\"true\" spellcheck=\"true\" class=\"texto\">NOTA</div>",
  "classesElemento": ["elemento-nota"],
  "recebePontoExtensor": true,
  "recebeSetaConectora": true,
  "propriedades": [
    {
      "chaveI18nLabel": "element.property.font-size.label",
      "classeElemento": "texto",
      "nomePropriedade": "style.font-size",
      "sufixo": "pt"
    },
    {
      "chaveI18nLabel": "element.property.height.label",
      "classeElemento": "elemento-nota",
      "nomePropriedade": "style.height",
      "sufixo": "px"
    },
    {
      "chaveI18nLabel": "element.property.width.label",
      "classeElemento": "elemento-nota",
      "nomePropriedade": "style.width",
      "sufixo": "px"
    },
    {
      "chaveI18nLabel": "element.property.text.label",
      "chaveI18nValorInicial": "element.property.default-name.note",
      "classeElemento": "texto",
      "nomePropriedade": "innerText",
      "sufixo": ""
    },
    {
      "chaveI18nLabel": "element.property.x.label",
      "classeElemento": "elemento-nota",
      "nomePropriedade": "style.left",
      "sufixo": "px"
    },
    {
      "chaveI18nLabel": "element.property.y.label",
      "classeElemento": "elemento-nota",
      "nomePropriedade": "style.top",
      "sufixo": "px"
    }
  ]
}

=== Heber-Modelo/heber-modelo/src/main/resources/static/elementos/conexao_angulada.json
{
  "$schema": ".elemento.schema.json",
  "valorHtmlInterno": "<div class=\"ponto ponto-norte\"><div class=\"ponto-norte-valor\"></div></div><div class=\"ponto ponto-sul\"><div class=\"ponto-sul-valor\"></div></div>",
  "classesElemento": ["elemento-conexao-angulada"],
  "recebePontoExtensor": false,
  "recebeSetaConectora": false,
  "propriedades": [
    {
      "chaveI18nLabel": "element.property.connection-type.label",
      "classeElemento": "elemento-conexao-angulada",
      "nomePropriedade": "connectionType",
      "sufixo": "",
      "chavesI18nLabelsValoresPermitidos": [
        "element.property-value.angled-connection.label",
        "element.property-value.weak-entity-connection.label",
        "element.property-value.arrow-connection.label"
      ],
      "valoresPermitidos": ["CONEXAO_ANGULADA", "CONEXAO_ENTIDADE_FRACA", "CONEXAO_SETA"]
    },
    {
      "chaveI18nLabel": "element.property.position-north-point.label",
      "classeElemento": "ponto-norte-valor",
      "nomePropriedade": "posicao-ponto-norte",
      "sufixo": "",
      "chavesI18nLabelsValoresPermitidos": [
        "element.property-value.north.label",
        "element.property-value.south.label",
        "element.property-value.east.label",
        "element.property-value.west.label"
      ],
      "valoresPermitidos": ["NORTE", "SUL", "LESTE", "OESTE"]
    },
    {
      "chaveI18nLabel": "element.property.position-south-point.label",
      "classeElemento": "ponto-sul-valor",
      "nomePropriedade": "posicao-ponto-sul",
      "sufixo": "",
      "chavesI18nLabelsValoresPermitidos": [
        "element.property-value.north.label",
        "element.property-value.south.label",
        "element.property-value.east.label",
        "element.property-value.west.label"
      ],
      "valoresPermitidos": ["NORTE", "SUL", "LESTE", "OESTE"]
    }
  ]
}

=== Heber-Modelo/heber-modelo/src/main/resources/static/elementos/agregacao.json
{
  "$schema": ".elemento.schema.json",
  "valorHtmlInterno": "<div class=\"losango-interno\"><div contenteditable=\"true\" spellcheck=\"true\" class=\"nome\">AGREGAÇÃO</div></div>",
  "classesElemento": ["elemento-agregacao"],
  "recebePontoExtensor": true,
  "recebeSetaConectora": true,
  "propriedades": [
    {
      "chaveI18nLabel": "element.property.font-size.label",
      "classeElemento": "nome",
      "nomePropriedade": "style.font-size",
      "sufixo": "pt"
    },
    {
      "chaveI18nLabel": "element.property.height.label",
      "classeElemento": "elemento-agregacao",
      "nomePropriedade": "style.height",
      "sufixo": "px"
    },
    {
      "chaveI18nLabel": "element.property.width.label",
      "classeElemento": "elemento-agregacao",
      "nomePropriedade": "style.width",
      "sufixo": "px"
    },
    {
      "chaveI18nLabel": "element.property.x.label",
      "classeElemento": "elemento-agregacao",
      "nomePropriedade": "style.left",
      "sufixo": "px"
    },
    {
      "chaveI18nLabel": "element.property.y.label",
      "classeElemento": "elemento-agregacao",
      "nomePropriedade": "style.top",
      "sufixo": "px"
    },
    {
      "chaveI18nLabel": "element.property.name.label",
      "chaveI18nValorInicial": "element.property.default-name.aggregation",
      "classeElemento": "nome",
      "nomePropriedade": "innerText",
      "sufixo": ""
    }
  ]
}

=== Heber-Modelo/heber-modelo/src/main/resources/static/elementos/entidade.json
{
  "$schema": ".elemento.schema.json",
  "valorHtmlInterno": "<div contenteditable=\"true\" spellcheck=\"true\" class=\"nome\">ENTIDADE</div>",
  "classesElemento": ["elemento-entidade"],
  "recebePontoExtensor": true,
  "recebeSetaConectora": true,
  "propriedades": [
    {
      "chaveI18nLabel": "element.property.font-size.label",
      "classeElemento": "nome",
      "nomePropriedade": "style.font-size",
      "sufixo": "pt"
    },
    {
      "chaveI18nLabel": "element.property.height.label",
      "classeElemento": "elemento-entidade",
      "nomePropriedade": "style.height",
      "sufixo": "px"
    },
    {
      "chaveI18nLabel": "element.property.width.label",
      "classeElemento": "elemento-entidade",
      "nomePropriedade": "style.width",
      "sufixo": "px"
    },
    {
      "chaveI18nLabel": "element.property.x.label",
      "classeElemento": "elemento-entidade",
      "nomePropriedade": "style.left",
      "sufixo": "px"
    },
    {
      "chaveI18nLabel": "element.property.y.label",
      "classeElemento": "elemento-entidade",
      "nomePropriedade": "style.top",
      "sufixo": "px"
    },
    {
      "chaveI18nLabel": "element.property.name.label",
      "chaveI18nValorInicial": "element.property.default-name.entity",
      "classeElemento": "nome",
      "nomePropriedade": "innerText",
      "sufixo": ""
    }
  ]
}

=== Heber-Modelo/heber-modelo/src/main/resources/static/elementos/relacionamento.json
{
  "$schema": ".elemento.schema.json",
  "valorHtmlInterno": "<div><div contenteditable=\"true\" spellcheck=\"true\" class=\"nome\">RELACIONAMENTO</div></div>",
  "classesElemento": ["elemento-relacionamento"],
  "recebePontoExtensor": true,
  "recebeSetaConectora": true,
  "propriedades": [
    {
      "chaveI18nLabel": "element.property.font-size.label",
      "classeElemento": "nome",
      "nomePropriedade": "style.font-size",
      "sufixo": "pt"
    },
    {
      "chaveI18nLabel": "element.property.name.label",
      "chaveI18nValorInicial": "element.property.default-name.relationship",
      "classeElemento": "nome",
      "nomePropriedade": "innerText",
      "sufixo": ""
    },
    {
      "chaveI18nLabel": "element.property.height.label",
      "classeElemento": "elemento-relacionamento",
      "nomePropriedade": "style.height",
      "sufixo": "px"
    },
    {
      "chaveI18nLabel": "element.property.width.label",
      "classeElemento": "elemento-relacionamento",
      "nomePropriedade": "style.width",
      "sufixo": "px"
    },
    {
      "chaveI18nLabel": "element.property.x.label",
      "classeElemento": "elemento-relacionamento",
      "nomePropriedade": "style.left",
      "sufixo": "px"
    },
    {
      "chaveI18nLabel": "element.property.y.label",
      "classeElemento": "elemento-relacionamento",
      "nomePropriedade": "style.top",
      "sufixo": "px"
    }
  ]
}

=== Heber-Modelo/heber-modelo/src/main/resources/static/elementos/classe.json
{
  "$schema": ".elemento.schema.json",
  "valorHtmlInterno": "<div class='nome-classe'>CLASSE</div><div class='atributos-classe'></div><div class='metodos-classe'></div>",
  "classesElemento": ["elemento-classe"],
  "recebePontoExtensor": true,
  "recebeSetaConectora": true,
  "propriedades": [
    {
      "chaveI18nLabel": "element.property.name.label",
      "chaveI18nValorInicial": "element.propery.default-value.class",
      "classeElemento": "nome",
      "nomePropriedade": "innerText",
      "sufixo": ""
    }
  ]
}

=== Heber-Modelo/heber-modelo/src/main/resources/static/elementos/cardinalidade.json
{
  "$schema": ".elemento.schema.json",
  "classesElemento": [
    "elemento-cardinalidade"
  ],
  "valorHtmlInterno": "<div class=\"tipo\">(0, N)</div>",
  "recebePontoExtensor": false,
  "recebeSetaConectora": false,
  "propriedades": [
    {
      "chaveI18nLabel": "element.property.cardinality.label",
      "classeElemento": "tipo",
      "nomePropriedade": "cardinalidade",
      "sufixo": "",
      "valoresPermitidos": ["(0, N)", "(1, N)", "(0, 1)", "(1, 1)"]
    },
    {
      "chaveI18nLabel": "element.property.height.label",
      "classeElemento": "elemento-cardinalidade",
      "nomePropriedade": "style.height",
      "sufixo": "px"
    },
    {
      "chaveI18nLabel": "element.property.width.label",
      "classeElemento": "elemento-cardinalidade",
      "nomePropriedade": "style.width",
      "sufixo": "px"
    },
    {
      "chaveI18nLabel": "element.property.x.label",
      "classeElemento": "elemento-cardinalidade",
      "nomePropriedade": "style.left",
      "sufixo": "px"
    },
    {
      "chaveI18nLabel": "element.property.y.label",
      "classeElemento": "elemento-cardinalidade",
      "nomePropriedade": "style.top",
      "sufixo": "px"
    },
    {
      "chaveI18nLabel": "element.property.font-size.label",
      "classeElemento": "tipo",
      "nomePropriedade": "style.font-size",
      "sufixo": "pt"
    }
  ]
}
